### ISSUE TITLE
PUT on records.json returns 204 instead of 200

### ISSUE THREAD

**Issue by jeffmikels** [lifechurch/churchmetrics-api#14]
When executing a PUT request on the records endpoint, a successful PUT results in a 204 response and does not return the record. This conflicts with the documentation which says this:

> This returns 200 OK if the update succeeded, along with the current JSON representation of the record in the response body.

**Comment by jeffmikels** [comment]
bump

**Comment by mattdeigh** [comment]
Thanks for the catch! I've updated the documentation.
