### ISSUE TITLE
Contribution Record Created, doesn't show up on website.

### ISSUE THREAD

**Issue by jeffmikels** [lifechurch/churchmetrics-api#15]
I have successfully created a contribution record using the API.

POST https://churchmetrics.com/api/v1/records.json

The response contained this:

```json
{"id":13305832,"organization_id":37879,"week_reference":2429,"service_date_time":"2016-07-24T15:45:00.000Z","service_timezone":"Eastern Time (US \u0026 Canada)","value":1750.0,"replaces":null,"created_at":"2017-01-05T06:09:48.939Z","updated_at":"2017-01-05T06:09:48.939Z","category":{"id":292839,"name":"Other Designated","format":"currency","kind":"Contributions","created_at":"2017-01-05T02:31:10.799Z","updated_at":"2017-01-05T04:46:28.435Z"},"campus":{"id":52284,"slug":"Lafayette Community Church","description":"Main gatherings","region_id":null,"timezone":"Eastern Time (US \u0026 Canada)","active":true,"created_at":"2016-02-01T03:07:58.063Z","updated_at":"2017-01-05T06:09:48.948Z"},"event":null}
```

The record is clearly in our Organization and I can query it by `id` using the api, but it doesn't show up on the website. Furthermore, if I use the website form to enter a contribution for that service, that amount will show up on the website, but BOTH amounts will show up in subsequent API queries.

The two records will exist and appear exactly the same in every respect except for `id`, `updated_at`, and `created_at`.

**Comment by jeffmikels** [comment]
bump

**Comment by jeffmikels** [comment]
Is anyone reading these?

**Comment by okcscott** [comment]
@jeffmikels can you paste the json for both records here, so we can track them down and compare them? Thanks.

**Comment by jeffmikels** [comment]
I ran my tests again today, and they seem to be working.
