### ISSUE TITLE
Categories improvement request

### ISSUE THREAD

**Issue by kylekurz** [lifechurch/churchmetrics-api#19]
The categories API response includes parent and child categories, but nothing to indicate which is which. Would be nice to add a parent attribute to the child categories with the ID of the parent in it. If there's another API available to get this info, please let me know.

**Comment by okcscott** [comment]
@kylekurz that's a good idea. I'm going to create a development task for this improvement. I don't have an ETA on when it would be released, however. But, I'll post back here when it's fixed.

**Comment by kylekurz** [comment]
Great thanks @okcscott. Out of curiosity, is there a different API that provides that information? I see your web view and your mobile app for input both "know" which are parent categories. The data being in the categories is ideal, but if I can combine two API requests in the interim, that'd be fine.

**Comment by okcscott** [comment]
@kylekurz Our web application is talking directly to the database, not through the API. And, the current mobile app is just a webview to the mobile website, which also is talking directly to the database. So, unfortunately, there is only 1 API to make requests from currently.

**Comment by kylekurz** [comment]
Well, that explains that, ha. I look forward to an update when you guys can get this included. 👍
