### ISSUE TITLE
Get API key using user's credentials

### ISSUE THREAD

**Issue by kylekurz** [lifechurch/churchmetrics-api#20]
I'm developing an app for our volunteer team to use for counting (big plus/minus buttons, etc) and need a way to get the API key out of the system using the user's email + pass credentials. This may be available since your app allows login via email+pass, but I don't see it documented in this repo.

**Comment by okcscott** [comment]
@kylekurz currently, there isn't an endpoint available for that. But, we could talk about adding the api key in the user objects that come back from the `/users` endpoint https://github.com/lifechurch/churchmetrics-api/blob/master/sections/users.md. Thoughts?

**Comment by kylekurz** [comment]
Well, the big thing is *some* API needs to be gated by username:password instead of username:api_key that lets me get the API key for later use. I'm fine with my first request being to that and getting back what is essentially a cookie (valid until the user resets it), but if I want the app I'm developing to be useful outside of a single user at a single church, I can't bundle in an API key to use for all requests and I'd like to be able to have multiple users from the same campus use the app individually.

As for your suggestion, that doesn't help with the need for an API key to authenticate *any* request currently.

**Comment by okcscott** [comment]
@kylekurz I understand. We are working on rebuilding the mobile app from the ground up. Part of it will include a new API for the app to consume. But, it will be a private API, and deviates from the authentication of the current API, so giving you access to the email/password authentication won't help, because the rest of the endpoints are app specific and not traditional restful routes, like our V1 API. And, there aren't plans to make it public at the moment. Sorry!

**Comment by kylekurz** [comment]
That makes the entire API essentially useless... Some way to use standard authentication to retrieve an API key is required. This is really disheartening.

**Comment by okcscott** [comment]
@kylekurz sorry to hear that. This version of the API has been in place for > 3 years, and you are the 1st person to have this request. I mentioned that our team is focused on rebuilding our mobile apps. After we get past that, we can see what adding this to the roadmap would look like.

**Comment by kylekurz** [comment]
So am I missing something here? If others are using this for any type of generic development (e.g. not for a specific single-user/church instance), how are they getting the API key? Seems unlikely that a user is willing to type in that token manually. 

I'm happy to work around this if you can point a way, I just don't see how to do this in a generic way without an API that let's me request a token.

**Comment by okcscott** [comment]
You can work around it by requiring the user to bring their API key, like this plugin someone developed for Wordpress https://wordpress.org/plugins/church-metrics-dashboard/. We've heard from lots of people that are using this plugin how much they enjoy it. So it appears that those users are at least comfortable with bringing their own API key. That's the only workaround that exists at this moment. Not conventional, but it is a "work around" that exists. You might reach out to the developer of it and ask for some pointers or ask if he has had pushback from bringing their API key to set it up. https://github.com/firetreedesign/church-metrics-dashboard
