### ISSUE TITLE
Records where updated_at > someDate?

### ISSUE THREAD

**Issue by cbh5g** [lifechurch/churchmetrics-api#21]
The URL below seems to return all records update_at that date, but can I query for all records updated **_since_** last week, or since yesterday?
https://churchmetrics.com/api/v1/records.json?updated_at=2016-08-07&page=pageNumber&per_page=100

I am working with an organization that has created their own roll-up categories for their metrics, so I'm trying to keep that system in sync, by querying on a scheduled interval, and only importing the rows updated since the last data pull.

Please let me know if you have any suggestions or input, or a fitting tech support contact?

Thank you!

**Comment by okcscott** [comment]
https://github.com/lifechurch/churchmetrics-api/blob/master/sections/records.md#get-records Have you tried leveraging the `start_time` parameter? You should be able to pass a timestamp in the format `"2012-03-27T17:00:00Z"` and it will return records after that timestamp.

**Comment by cbh5g** [comment]
Ok, thank you very much Scott, I will look into that, and see if it will work.  THANK YOU!   :)

**Comment by okcscott** [comment]
@cbh5g I'm going to close this issue for now. If that parameter doesn't do the trick, feel free to re-open and comment back.
