### ISSUE TITLE
API Improvement: Request service times for specific campus

### ISSUE THREAD

**Issue by kylekurz** [lifechurch/churchmetrics-api#22]
Would be nice to have a parameter on the service_times API that lets me only get services for a specific campus id, rather than getting the whole list of all services at all campuses and having to filter them. Would also lower data transfer, which is good for users and probably your backend.

**Comment by okcscott** [comment]
@kylekurz hey Kyle. Loving the uptick in interest around our API. Could you and I connect? Would love to know more about you, projects you're on, church you serve at, etc etc. My email is scott.lesser@life.church.
