### ISSUE TITLE
What exactly is week_reference?

### ISSUE THREAD

**Issue by danielmilner** [lifechurch/churchmetrics-api#6]
Where does `week_reference`, `start_week`, and `end_week` come from? How is it calculated/determined?

**Comment by mattdeigh** [comment]
Hey Daniel! Sorry, I wasn't watching this repo. The ```week_reference``` is how many weeks since epoch. Here's the code we use to generate it. The start and end week are both week references.

```ruby
DateCalc.epoch_weeks(Date.today)
```
```ruby
module DateCalc

  # Returns the amount of weeks since the first Sunday epoch (jan 4, 1970)
  def self.epoch_weeks(date)
    date = date.to_date if date.kind_of?(Time)
    (date - Date.new(1970, 1, 4)).to_i / 7
  end

end
```

**Comment by danielmilner** [comment]
Thanks for the clarification.

I don't know why i asked about `start_week` and `end_week`. Those were pretty straight forward.
